### ISSUE TITLE
Adding in arduino libraries fails on credentials

### ISSUE THREAD

**Issue by andrewtholt** [Seeed-Studio/ardupy-aip#3]
Hi, 

I execute the following:
```bash
aip install Seeed-Studio/seeed-ardupy-ultrasonic-sensor
```
And get the following:
```bash
Downloading library......
User for github.com: andrewtholt
Password: 
Save credentials to keyring [y/N]: 
Your response ('') was not one of the expected responses: y, n
Save credentials to keyring [y/N]: N
WARNING: 401 Error, Credentials not correct for https://github.com/Seeed-Studio/seeed-ardupy-ultrasonic-sensor/archive/master.zip
ERROR: HTTP error 401 while getting https://github.com/Seeed-Studio/seeed-ardupy-ultrasonic-sensor/archive/master.zip
ERROR: 401 Client Error: Unauthorized for url: https://github.com/Seeed-Studio/seeed-ardupy-ultrasonic-sensor/archive/master.zip
```
I can download the zip file from github with a browser, and with wget.

**Comment by LynnL4** [comment]
Hi，
Can you download the compressed package normally through the following link?
```https://github.com/Seeed-Studio/seeed-ardupy-ultrasonic-sensor/archive/master.zip```
This seems to be the problem with GitHub.

**Comment by LynnL4** [comment]
try reinstall ardupy-aip by pip3. Can you provide version information of the system you are using

**Comment by andrewtholt** [comment]
aip -V
aip (0.6.0) - ArduPy Integrated Platform is a utility to develop ArduPy and
interact witch ArduPy board.

**Comment by LynnL4** [comment]
I mean the version of the operating system, for example macos 10.15

**Comment by andrewtholt** [comment]
Sorry Ubuntu 18.04

**Comment by LynnL4** [comment]
Have you ever tried to reply y?

**Comment by andrewtholt** [comment]
Sorry, the OS is Ubuntu 18.04

**Comment by LynnL4** [comment]
Save credentials to keyring [y/N]: y

**Comment by andrewtholt** [comment]
I'll give it a try, and let you know.
