### ISSUE TITLE
aip depends on pip internals breaks with pip 20.3.3

### ISSUE THREAD

**Issue by jischebeck** [Seeed-Studio/ardupy-aip#8]
Running AIP on a windows system with Python3.9 and PIP 20.3.3 leads to the following error:

```
PS C:\WINDOWS\system32> aip                                                                                             
Traceback (most recent call last):
  File "c:\python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python39\Scripts\aip.exe\__main__.py", line 7, in <module>
  File "c:\python39\lib\site-packages\aip\main.py", line 52, in main
    from aip.command import commands_dict, parse_command
  File "c:\python39\lib\site-packages\aip\command.py", line 46, in <module>
    from aip.build import buildCommand
  File "c:\python39\lib\site-packages\aip\build.py", line 34, in <module>
    from pip._internal.operations.prepare import (
ImportError: cannot import name '_download_http_url' from 'pip._internal.operations.prepare' (c:\python39\lib\site-packages\pip\_internal\operations\prepare.py)

```

**Comment by jischebeck** [comment]
Removing "_download_http_url" import from uninstall.py, flash.py, install.py, build.py and shell.py seems to fix the issue, as the import is not used at all.

**Comment by karma0** [comment]
I'm getting this as well, running Arch Linux with Python `3.9.1` and Pip version `20.3.3`.

**Comment by karma0** [comment]
For what it's worth, people aren't supposed to be using `pip._internals`, hence the `_` to denote the private space.  This part of the pip toolkit are intended to support the package manager, but not meant to be used externally and may result in code breakages for external libraries.  Using it will create a lot of work for you guys.

That being said, I found a workaround:

- downgrade to `pip==20.2.4`
- install `requests` to your environment (it's not in the `requirements.txt` file provided with the project).

**Comment by robertpeteuil** [comment]
Same problem on macOS, as Python 3.9 is now the default Python when installed via `brew` (which ironically is specifically how the Wiki suggests installing it.)

**Comment by robertpeteuil** [comment]
> Removing "_download_http_url" import from uninstall.py, flash.py, install.py, build.py and shell.py seems to fix the issue, as the import is not used at all.

It looks like _download_http_url may be used in some situation, as after making this change I get this error when trying to install packages:

```sh
$ aip install https://github.com/Crazyhackelkorn/seeed-ardupy-sdcard
Downloading library......
ERROR: unpack_url() got an unexpected keyword argument 'downloader'
```

**Comment by Pillar1989** [comment]
I hate that pip always modifying its own interface, what do you guys suggest, I want to fix this problem completely.

**Comment by terop** [comment]
Do not use Pip internal functionality (things starting with an underscore). The excellent requests library has been mentioned before and is a very good choice for HTTP operations.

**Comment by BobKerns** [comment]
I worked around this and the above-mentioned unpack_url() issue, which I documented here:

https://forum.seeedstudio.com/t/install-aip-on-mac-high-sierra/255611/15

@jischebeck is correct that \_download_http_url is not used at all; that was part of my fixing.

**Comment by BobKerns** [comment]
I did not investigate or fix any other pip internal dependencies—just the ones that were failing. Any that remain should be cleaned up too, to avoid future failures. But for now, this works.
